# Generated by Django 5.2.15 on 2026-06-25 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_custome_70b027_idx',
            old_name='transaction_custome_0f8e2d_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_custome_5532fd_idx',
            old_name='transaction_custome_6a3b1f_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_transac_6c78ef_idx',
            old_name='transaction_transac_9d4c2a_idx',
        ),
    ]
