# Generated by Django 5.2.15 on 2026-06-26 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_versioning'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_custome_99a7e5_idx',
            old_name='transaction_custome_5f0a8a_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_root_tr_72167c_idx',
            old_name='transaction_root_tr_7d2f1e_idx',
        ),
    ]
