# Generated by Django 5.2.15 on 2026-06-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_halkhata'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_halkhat_eefce6_idx',
            old_name='transaction_halkhat_8a1c2d_idx',
        ),
    ]
