# Generated by Django 5.2.15 on 2026-06-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_bilingual_phone_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='memo_page_number_bn',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_bn',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_en',
            field=models.CharField(max_length=20),
        ),
    ]
