# Generated by Django 5.2.15 on 2026-06-26 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customer_archive_customerversion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customerversion',
            new_name='customers_c_custome_b82928_idx',
            old_name='customers_c_custome_0d0f0d_idx',
        ),
    ]
