# Generated by Django 5.2.14 on 2026-06-10 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_bn', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'division',
                'verbose_name_plural': 'divisions',
                'ordering': ['name_en'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_bn', models.CharField(max_length=255)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='geo.division')),
            ],
            options={
                'verbose_name': 'district',
                'verbose_name_plural': 'districts',
                'ordering': ['name_en'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Upazila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_bn', models.CharField(max_length=255)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upazilas', to='geo.district')),
            ],
            options={
                'verbose_name': 'upazila',
                'verbose_name_plural': 'upazilas',
                'ordering': ['name_en'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_bn', models.CharField(max_length=255)),
                ('upazila', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unions', to='geo.upazila')),
            ],
            options={
                'verbose_name': 'union',
                'verbose_name_plural': 'unions',
                'ordering': ['name_en'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['division'], name='geo_distric_divisio_2218d1_idx'),
        ),
        migrations.AddIndex(
            model_name='upazila',
            index=models.Index(fields=['district'], name='geo_upazila_distric_e4ed9b_idx'),
        ),
        migrations.AddIndex(
            model_name='union',
            index=models.Index(fields=['upazila'], name='geo_union_upazila_a8422d_idx'),
        ),
    ]
