# Generated by Django 5.2.15 on 2026-06-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_explicit_geo_primary_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('name_en', models.CharField(max_length=255)),
                ('name_bn', models.CharField(max_length=255)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'village',
                'verbose_name_plural': 'villages',
                'ordering': ['name_en'],
                'abstract': False,
            },
        ),
    ]
