# Generated by Django 5.2.15 on 2026-06-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halkhata', '0002_invitation_generations'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='halkhatainvitationgeneration',
            new_name='halkhata_ha_halkhat_e52b68_idx',
            old_name='halkhata_hal_halkhat_0f0f0f_idx',
        ),
        migrations.RenameIndex(
            model_name='halkhatainvitationrecipientsnapshot',
            new_name='halkhata_ha_generat_2d9cf0_idx',
            old_name='halkhata_hal_generat_1a1a1a_idx',
        ),
    ]
