import type { DashboardData } from '@razzak-machinaries/shared/api';

export const sampleDashboardData: DashboardData = {
  summary: {
    totalDue: '1700.00',
    currentMonthSales: '1000.00',
    currentMonthPayments: '200.00',
    currentMonthNetDueChange: '800.00',
    totalCustomers: 2,
    totalTransactions: 4,
  },
  recentTransactions: [
    {
      id: 2,
      displayId: 'COM-2',
      customerId: 1,
      customerNameBn: 'আলী',
      customerNameEn: 'Ali',
      transactionType: 'SALE',
      date: '2026-01-10',
      totalAmount: '1000.00',
      updatedAt: '2026-01-10T12:00:00Z',
    },
    {
      id: 3,
      displayId: 'COM-3',
      customerId: 1,
      customerNameBn: 'আলী',
      customerNameEn: 'Ali',
      transactionType: 'PAYMENT',
      date: '2026-01-20',
      totalAmount: '200.00',
      updatedAt: '2026-01-20T12:00:00Z',
    },
    {
      id: 1,
      displayId: 'COM-1',
      customerId: 1,
      customerNameBn: 'আলী',
      customerNameEn: 'Ali',
      transactionType: 'INITIAL',
      date: '2025-06-01',
      totalAmount: '1000.00',
      updatedAt: '2025-06-01T12:00:00Z',
    },
  ],
  recentCustomers: [
    {
      id: 1,
      fullNameBn: 'আলী',
      fullNameEn: 'Ali',
      phone: '+8801711111111',
      addressBn: 'ঠিকানা',
      addressEn: 'Address',
      currentBalance: '1400.00',
      updatedAt: '2026-01-20T12:00:00Z',
    },
  ],
  yearlyStats: {
    year: 2026,
    monthlySalesPayments: Array.from({ length: 12 }, (_, index) => ({
      month: index + 1,
      monthName: [
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December',
      ][index],
      sales: index === 0 ? '1000.00' : '0',
      payments: index === 0 ? '200.00' : '0',
    })),
    monthlyDueChange: Array.from({ length: 12 }, (_, index) => ({
      month: index + 1,
      monthName: [
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December',
      ][index],
      netDueChange: index === 0 ? '800.00' : '0',
    })),
    monthlyTransactionCounts: Array.from({ length: 12 }, (_, index) => ({
      month: index + 1,
      monthName: [
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December',
      ][index],
      salesCount: index === 0 ? 1 : 0,
      paymentsCount: index === 0 ? 1 : 0,
      initialCount: 0,
    })),
    topCustomersByDue: [
      {
        customerId: 1,
        customerNameBn: 'আলী',
        customerNameEn: 'Ali',
        currentBalance: '1400.00',
      },
    ],
    yearlySalesTotal: '1000.00',
    yearlyPaymentsTotal: '200.00',
    availableYears: [2025, 2026],
  },
};
